Fix/Ui Kit Issues
defactor-com/ui-kit pull request #211
Opened 2024-05-23 17:11 UTC by JAMares

## Ui Kit Issues

### What does this PR do?

- Resolve #207 
- Resolve #208 
- Resolve #209 

### Steps to test

1. Run project
2. Check changes

#### CheckList

- [X] Follow proper Markdown format
- [X] Content is available in all languages
- [X] The content is adequate
- [X] I Ran a spell check
- [X] I included test coverage

2024-05-23 18:22 UTC, AngeloCG97 requested changes
Issue https://github.com/defactor-com/ui-kit/issues/209 are resolved on this PR?

2024-05-23 18:39 UTC, JAMares commented
My error is #210

2024-05-23 19:12 UTC, AngeloCG97 requested changes
Please create change set file to generate new version

2024-05-24 14:42 UTC, AngeloCG97 approved these changes

2024-05-24 14:43 UTC, merged