Feat/avoid repetitive values when the filter is day and value does not change 259
defactor-com/ui-kit pull request #263
Opened 2024-06-13 18:17 UTC by JAMares

## Avoid repetitive values when the filter is day and value does not change

### What does this PR do?

- Resolve #259

### Steps to test

1. Run `yarn storybook`
2. Check performance

Now:

https://github.com/defactor-com/ui-kit/assets/49013556/7a2454a9-c845-4aa8-aa36-3450d1ea4154

#### CheckList

- [X] Follow proper Markdown format
- [X] Content is available in all languages
- [X] The content is adequate
- [X] I Ran a spell check
- [X] I included test coverage

2024-06-13 19:22 UTC, AngeloCG97 requested changes
This space is necessary?

2024-06-13 19:23 UTC, AngeloCG97 commented on src/components/LineChart/useLineChartState.tsx
> +    const hideSeries = Object.keys(hide).filter((clave) => hide[clave]);
Please add space before if condition

2024-06-13 19:24 UTC, AngeloCG97 commented on src/components/LineChart/useLineChartState.tsx
> +      if (isSameData) setTickCount(1);
same

2024-06-13 19:24 UTC, AngeloCG97 commented on src/stories/LineChart.stories.tsx
> +  // formatValue,
this comment is necessary?

2024-06-14 15:48 UTC, xavier506 commented on src/stories/LineChart.stories.tsx
> +  let numeroStr = value.toString();
@JAMares  can we stick to english names for variables please

2024-06-14 19:13 UTC, JAMares commented on src/stories/LineChart.stories.tsx
> +  let numeroStr = value.toString();
Fixed it

2024-06-14 20:51 UTC, xavier506 commented on src/stories/LineChart.stories.tsx
> +  let firtsDigits = numberStr.slice(0, 2);
first not firts

2024-06-14 21:26 UTC, AngeloCG97 approved these changes

2024-06-14 21:27 UTC, merged