feat(components): created loader and pagination components on table
defactor-com/ui-kit pull request #71
Opened 2024-03-05 22:36 UTC by AngeloCG97

## Created loader and pagination components on table

### What does this PR do?

- Resolve #67

2024-03-05 23:44 UTC, leisterfrancisco requested changes

2024-03-05 23:44 UTC, leisterfrancisco commented on dist/index.css
Is dist folder necessary?

2024-03-05 23:44 UTC, leisterfrancisco commented on src/stories/Table.stories.tsx
> +          <span>cargando...</span>
should it be loaded from i18 solution?

Why spanish?

2024-03-06 07:58 UTC, xavier506 reviewed
can we integrate i18n ?

2024-03-06 13:58 UTC, AngeloCG97 commented on src/stories/Table.stories.tsx
> +          <span>cargando...</span>
These are sample texts for the webapp storybook, not for the library.

2024-03-06 13:59 UTC, AngeloCG97 commented on src/components/Table/index.tsx
> +                Rows per page:
I will receive this text as a parameter for the component and have the person who integrates it send the text in the language they want.

2024-03-06 20:59 UTC, xavier506 approved these changes
LGTM

2024-03-06 20:59 UTC, merged