feat(table): add filters
defactor-com/ui-kit pull request #78
Opened 2024-03-14 19:23 UTC by JAMares

## Add filters

### What does this PR do?

- Resolve #55 

### Steps to test

1. Run project
2. Check changes

Before:

Now:
![imagen](https://github.com/defactor-com/ui-kit/assets/49013556/df6e1f58-3574-41d9-ab58-7cbd55e00d38)

#### CheckList

- [X] Follow proper Markdown format
- [X] Content is available in all languages
- [X] The content is adequate
- [X] I Ran a spell check
- [X] I included test coverage

2024-03-14 22:03 UTC, leisterfrancisco approved these changes

2024-03-14 22:03 UTC, leisterfrancisco commented on src/stories/Table.stories.tsx
> +      setFilters={SetData}
should `SetData` use Pascal Case?

2024-03-14 22:03 UTC, leisterfrancisco commented on src/components/Table/index.tsx
> +  const updateDate = () => {
Why Date? isn't it Data?

2024-03-14 22:04 UTC, leisterfrancisco requested changes
please, see my comment, by mistake I clicked approve instead of request

2024-03-15 14:28 UTC, JAMares commented on src/stories/Table.stories.tsx
> +  }, [data]);
This PR is current WIP, is for test

2024-03-15 14:29 UTC, JAMares commented on src/components/Table/index.tsx
> +  const updateDate = () => {
Fixed it

2024-03-15 16:51 UTC, Edwinjrc approved these changes
LGTM

2024-03-15 16:59 UTC, leisterfrancisco approved these changes

2024-03-15 16:59 UTC, leisterfrancisco commented on src/stories/Table.stories.tsx
> +const dataTable = [
rename it to tableData

2024-03-15 19:36 UTC, xavier506 commented
@JAMares  lets add a date selector a a multiple selection droprdown for status filters

2024-03-18 13:57 UTC, leisterfrancisco requested changes

2024-03-18 13:57 UTC, leisterfrancisco commented on src/components/Table/index.tsx
> +  type?: "multiple" | "date";
since it can only be multiple or date, should it be optional?

2024-03-18 16:31 UTC, xavier506 commented on src/stories/DropDown.stories.tsx
> +  "Oliver Hansen",
What is this list of names?

2024-03-18 17:42 UTC, merged

2024-03-18 19:10 UTC, leisterfrancisco commented
@JAMares this interface

export interface IFilterObject {
  label: string;
  options?: string[];
  type?: "multiple" | "date"; 
}

`type` should not be optional