Feat/enhance chart component 72
defactor-com/ui-kit pull request #79
Opened 2024-03-14 22:08 UTC by Torresmorah

## Enhance Dashboard Component

### What does this PR do?

- Resolve #72 
- Allow to have as many lines and bottom items as needed
- Allow to enable and disable the lines in the chart
- Allow to pass a function to format the numbers
- Add a CardComponent to replace FlatComponent in the Dashboard
- Remove currency label from the cards

### Steps to test

1. Run the project locally
2. Go to Dashboard component section
3. Check the Component

### Screenshots

**Desktop**

![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/8b2c7e71-dbad-467c-9607-d177c265084c)
![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/6441c12a-e6a2-4e75-84de-576163f68dc5)

**Tablet**

![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/1a09387b-4c71-4cf7-9eb4-ad7c74a2c146)

**Mobile**

![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/6d406d33-b5fc-462a-adbc-888d7a0b3ef3)

2024-03-14 22:29 UTC, xavier506 commented
@Torresmorah  can you please also take a look at this issue #76

2024-03-14 23:06 UTC, Edwinjrc approved these changes
LGTM

2024-03-14 23:38 UTC, leisterfrancisco commented
@Edwinjrc @Torresmorah dollar symbol in the top left section is repetitive, `$...usdc`

2024-03-14 23:44 UTC, leisterfrancisco requested changes

2024-03-14 23:44 UTC, leisterfrancisco commented on src/components/Graphic/index.tsx
> +import { Point } from "../Point";
let's leave a blank line to divide project imports and local imports

2024-03-14 23:44 UTC, leisterfrancisco commented on src/stories/Dashboard.stories.tsx
> +  }`
There is already a method for this type of formatting, please use it

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#using_tolocalestring

2024-03-15 17:09 UTC, leisterfrancisco approved these changes

2024-03-15 17:09 UTC, leisterfrancisco commented on src/components/Dashboard/index.tsx
> +};
is `;` required?

2024-03-15 17:09 UTC, leisterfrancisco commented on src/components/Dashboard/index.tsx
> +};
maybe prettier is not configured correctly, would be nice to set it up in that case

2024-03-16 13:55 UTC, xavier506 approved these changes
lgtm

2024-03-16 13:55 UTC, merged