Feat/add pie and bar charts 73 74
defactor-com/ui-kit pull request #83
Opened 2024-03-19 21:41 UTC by Torresmorah

## Add Bar Chart, Pie Chart and refactor Dashboard component to customize the content

### What does this PR do?

- Resolve #73
- Resolve #74
- Refactor Dashboard to receive the main content and the items from the right column as params
- Add simple tooltip to the Bar and Pie Chart
- Update to 0.0.46 version

### Steps to test

1. Run the project locally
2. Go to Dashboard component
3. Check the three examples

### Screenshots

**Stories**

![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/dff960b7-e806-48bc-85b2-8309204886e3)

**Desktop breakpoint**

![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/5b11d16b-0637-46ff-8202-007ebf3e0799)
![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/865b46de-b1d4-4e62-b591-557c9b06af4b)
![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/78c35de9-5871-45b7-ae8a-70463b58a88d)
![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/54c15999-61bc-46a2-8563-91e5c198a94c)

**Mobile breakpoint**

![imagen](https://github.com/defactor-com/ui-kit/assets/66583677/b37f5bff-1013-4760-8ecd-f50dc537f315)

2024-03-19 22:32 UTC, xavier506 commented
@Torresmorah  please resolve conflict

2024-03-19 23:56 UTC, leisterfrancisco requested changes

2024-03-19 23:56 UTC, leisterfrancisco commented on src/stories/BarChart.stories.tsx
> +const formatValue = (value: number, options?: Intl.NumberFormatOptions) => {
avoid the usage of number, instead, use bigint.

Please check a function in utils/functions that have a similar method to format a number.

2024-03-19 23:56 UTC, leisterfrancisco commented on src/stories/Dashboard.stories.tsx
> +  { label: "Loan to Value Ratio", value: "75%" },
i18n

2024-03-19 23:56 UTC, leisterfrancisco commented on src/stories/Dashboard.stories.tsx
> +  { label: "Loans Ready to Borrows", value: 2500 },
i18n

2024-03-19 23:56 UTC, leisterfrancisco commented on src/stories/PieChart.stories.tsx
> +];
i18n

2024-03-20 13:47 UTC, xavier506 commented on src/stories/Dashboard.stories.tsx
> +  { label: "Total Borrows Repaid", value: 200 },
Total Loans Repaid

2024-03-20 13:47 UTC, xavier506 commented on src/stories/Dashboard.stories.tsx
> +  { label: "Total Debt", value: 800 },
Total Loans

2024-03-20 13:47 UTC, xavier506 commented on src/stories/Dashboard.stories.tsx
> +  { label: "Next Borrow to Reach Maturity", value: 'Pool B' },
Next Loan to Reach...

2024-03-20 13:48 UTC, xavier506 commented on src/stories/Dashboard.stories.tsx
> +      chartSubtitle="Pool by Status"
Pools by Status

2024-03-20 15:45 UTC, leisterfrancisco approved these changes

2024-03-20 17:10 UTC, xavier506 approved these changes
LGTM

2024-03-20 17:10 UTC, merged